image:
- Visual Studio 2022
- Ubuntu2004

# Java 9+ not supported by XMLBeans
stack: jdk 8

for:
  - matrix:
      only:
        - image: Visual Studio 2022
    cache:
      - '%USERPROFILE%\.m2 -> **\pom.xml'
  - matrix:
      only:
        - image: Ubuntu
    cache:
      - '$HOME/.m2 -> **/pom.xml'

build_script:
  # Java 9+ not supported by XMLBeans
  - cmd: set JAVA_HOME=C:\Program Files\Java\jdk1.8.0\jre
  - cmd: mvn package

  - sh: mvn package

artifacts:
  - path: 'target\*.jar'
