image:
- Visual Studio 2017
- Ubuntu

# Java 9+ not supported by XMLBeans
stack: jdk 8

build_script:
  # Java 9+ not supported by XMLBeans
  - cmd: set JAVA_HOME=C:\Program Files\Java\jdk1.8.0\jre
  - cmd: mvn package

  - sh: mvn package

artifacts:
  - path: 'target\*.jar'
